/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.polysfactory.objectrecognition.jni;

import com.opencv.jni.image_pool;// import the image_pool interface for playing nice with
								 // android-opencv

/** Processor - for processing images that are stored in an image pool
*/
public class Processor {
  private long swigCPtr;
  protected boolean swigCMemOwn;
  public Processor(long cPtr, boolean cMemoryOwn) {
	swigCMemOwn = cMemoryOwn;
	swigCPtr = cPtr;
  }
  public static long getCPtr(Processor obj) {
	return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      cvcameraJNI.delete_Processor(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Processor() {
    this(cvcameraJNI.new_Processor(), true);
  }

  public int detectAndDrawFeatures(int idx, image_pool pool) {
    return cvcameraJNI.Processor_detectAndDrawFeatures(swigCPtr, this, idx, image_pool.getCPtr(pool), pool);
  }

  public boolean loadDescription(String filename) {
    return cvcameraJNI.Processor_loadDescription(swigCPtr, this, filename);
  }

}
